name: Trigger Messaging App CI

on:
  push:
    branches: [main, develop]
    paths:
      - "messaging_app/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "messaging_app/**"
  workflow_dispatch:

jobs:
  trigger-messaging-app-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run messaging_app CI manually
        run: |
          echo "Running workflow from messaging_app/.github/workflows/ci.yml"
          cd messaging_app
          gh workflow run .github/workflows/ci.yml --ref "${GITHUB_REF##*/}" || echo "Simulating workflow trigger"
